# Generated by Django 3.2 on 2024-04-26 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Events',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
    #             ('event_description', models.CharField(max_length=255, verbose_name='Event Description')),
    #             ('event_date', models.DateField(verbose_name='Event Date')),
    #             ('event_status', models.CharField(max_length=11, verbose_name='Event Status')),
    #             ('location', models.CharField(max_length=255, verbose_name='Location')),
    #             ('organizer', models.CharField(max_length=255, verbose_name='Organizer')),
    #         ],
    #     ),
    #     migrations.CreateModel(
    #         name='Student',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('student_id', models.CharField(max_length=11, verbose_name='Student ID')),
    #             ('student_first_name', models.CharField(max_length=50, verbose_name='First Name')),
    #             ('student_middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
    #             ('student_last_name', models.CharField(max_length=50, verbose_name='Last Name')),
    #             ('department', models.CharField(max_length=50, verbose_name='Department')),
    #             ('course', models.CharField(max_length=50, verbose_name='Course')),
    #         ],
    #     ),
    #     migrations.CreateModel(
    #         name='StudentProfile',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('is_student', models.BooleanField(default=False)),
    #             ('is_face_registered', models.BooleanField(default=False)),
    #             ('default_password', models.CharField(max_length=128, null=True)),
    #             ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='app_no_bull.student')),
    #             ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
    #         ],
    #     ),
    #     migrations.CreateModel(
    #         name='StudentAttendance',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('is_attend', models.BooleanField(default=False)),
    #             ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='events_profile', to='app_no_bull.events')),
    #             ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='app_no_bull.student')),
    #         ],
    #     ),
    # ]
