# Generated by Django 3.2 on 2024-04-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_no_bull', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('event_description', models.CharField(max_length=255, verbose_name='Event Description')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('event_status', models.CharField(max_length=11, verbose_name='Event Status')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('organizer', models.CharField(max_length=255, verbose_name='Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=11, verbose_name='Student ID')),
                ('student_first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('student_middle_name', models.CharField(max_length=50, verbose_name='Middle Name')),
                ('student_last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('course', models.CharField(max_length=50, verbose_name='Course')),
            ],
        ),
    ]
