# Generated by Django 3.2 on 2024-04-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0003_studentattendance_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='is_attend',
            new_name='is_attend_time_in',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='is_attend_time_out',
            field=models.BooleanField(default=False),
        ),
    ]
