# Generated by Django 3.2 on 2024-04-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0004_auto_20240428_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='time_of_time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='time_of_time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
