# Generated by Django 3.2 on 2024-04-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0005_auto_20240428_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='time_of_time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='time_of_time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
