# Generated by Django 3.2 on 2024-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0006_auto_20240428_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
