# Generated by Django 3.2 on 2024-09-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0007_events_event_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_rfid',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
