# Generated by Django 3.2 on 2024-09-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0008_studentprofile_student_rfid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='is_face_registered',
            new_name='is_rfid_registered',
        ),
    ]
