# Generated by Django 3.2 on 2024-09-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0009_rename_is_face_registered_studentprofile_is_rfid_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_profile', to='app_no_bull.events'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='app_no_bull.student'),
        ),
        migrations.CreateModel(
            name='StudentFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_paid_fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_paid_fine_date', models.DateField(verbose_name='Transaction Date')),
                ('student_fine_remarks', models.CharField(max_length=255, verbose_name='Remarks')),
                ('student_fine_status', models.CharField(max_length=11, verbose_name='Fine Status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fines', to='app_no_bull.student')),
            ],
        ),
    ]
