# Generated by Django 3.2 on 2024-09-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0010_auto_20240913_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='is_attendance_paid',
            field=models.BooleanField(default=False),
        ),
    ]
