# Generated by Django 3.2 on 2024-09-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0011_studentattendance_is_attendance_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfine',
            name='student_fine_status',
        ),
    ]
