# Generated by Django 3.2 on 2024-09-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0012_remove_studentfine_student_fine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='studentfine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fine', to='app_no_bull.studentfine'),
        ),
    ]
