# Generated by Django 3.2 on 2024-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0013_studentattendance_studentfine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfine',
            name='student_paid_fine_date',
        ),
        migrations.AddField(
            model_name='studentfine',
            name='student_paid_fine_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
