# Generated by Django 3.2 on 2024-09-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0014_auto_20240917_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_rfid',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
