# Generated by Django 3.2 on 2024-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0015_alter_studentprofile_student_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfine',
            name='student_fine_remarks',
            field=models.TextField(verbose_name='Remarks'),
        ),
    ]
