# Generated by Django 3.2 on 2024-09-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0016_alter_studentfine_student_fine_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfine',
            name='student_fine_status',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.TextField(verbose_name='Event Description'),
        ),
    ]
