# Generated by Django 3.2 on 2024-09-27 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_no_bull', '0017_auto_20240921_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant_fullname', models.CharField(max_length=50, verbose_name='Full Name')),
                ('contestant_department', models.CharField(max_length=50, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category Name')),
                ('criteria_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage')),
            ],
        ),
        migrations.CreateModel(
            name='EventTabulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('et_event_name', models.CharField(max_length=255, verbose_name='Event Tabulation Name')),
                ('et_event_description', models.TextField(verbose_name='Event Tabulation Description')),
                ('et_event_date', models.DateField(verbose_name='Event Tabulation Date')),
                ('et_event_status', models.CharField(max_length=11, verbose_name='Tabulation Status')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('organizer', models.CharField(max_length=255, verbose_name='Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_firstname', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('judge_lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('judge_moredetails', models.TextField(blank=True, null=True, verbose_name='More Details')),
            ],
        ),
        migrations.AddField(
            model_name='studentfine',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fines', to='auth.group'),
        ),
        migrations.AddField(
            model_name='studentfine',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Transaction Number'),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='auth.group', verbose_name='Organizer'),
        ),
        migrations.CreateModel(
            name='JudgeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_judge', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('default_password', models.CharField(max_length=128, null=True)),
                ('judge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to='app_no_bull.judge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='app_no_bull.contestant')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app_no_bull.criteria')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app_no_bull.judge')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='event_tabulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_event_tabulation', to='app_no_bull.eventtabulation'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='event_tabulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant_event_tabulation', to='app_no_bull.eventtabulation'),
        ),
    ]
