# Generated by Django 3.2 on 2024-09-30 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_no_bull', '0018_auto_20240927_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfine',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.TextField(blank=True, null=True, verbose_name='Event Description'),
        ),
        migrations.AlterField(
            model_name='eventtabulation',
            name='et_event_description',
            field=models.TextField(blank=True, null=True, verbose_name='Event Tabulation Description'),
        ),
    ]
