# Generated by Django 3.2 on 2024-10-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_no_bull', '0019_auto_20240930_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='event_tabulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_event_tabulation', to='app_no_bull.eventtabulation'),
        ),
    ]
