# Generated by Django 4.2.16 on 2024-11-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_no_bull", "0020_judge_event_tabulation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentfine",
            name="transaction_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Transaction Number",
            ),
        ),
    ]
