# Generated by Django 4.2.16 on 2025-04-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_no_bull", "0021_alter_studentfine_transaction_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher_id",
                    models.CharField(max_length=11, verbose_name="Teacher ID"),
                ),
                (
                    "teacher_first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "teacher_middle_name",
                    models.CharField(max_length=50, verbose_name="Middle Name"),
                ),
                (
                    "teacher_last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "department",
                    models.CharField(max_length=50, verbose_name="Department"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_classroom",
                        to="app_no_bull.teacher",
                    ),
                ),
            ],
        ),
    ]
