# Generated by Django 4.2.16 on 2025-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_no_bull", "0023_teacherprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="classroom_description",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Classroom Name"
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="classroom_status",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Classroom Status"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="classroom_name",
            field=models.CharField(max_length=50, verbose_name="Classroom Name"),
        ),
    ]
