# Generated by Django 4.2.16 on 2025-04-16 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_no_bull", "0024_classroom_classroom_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="classroom_description",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Description"
            ),
        ),
        migrations.CreateModel(
            name="BullyingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_speech",
                    models.CharField(max_length=255, verbose_name="Detected Speech"),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "audio_clip_path",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Audio Path"
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_bullevent",
                        to="app_no_bull.classroom",
                    ),
                ),
            ],
        ),
    ]
