# Generated by Django 4.2.16 on 2025-04-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_no_bull", "0025_alter_classroom_classroom_description_bullyingevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="criteria",
            name="event_tabulation",
        ),
        migrations.RemoveField(
            model_name="criteriascores",
            name="contestant",
        ),
        migrations.RemoveField(
            model_name="criteriascores",
            name="criteria",
        ),
        migrations.RemoveField(
            model_name="criteriascores",
            name="judge",
        ),
        migrations.RemoveField(
            model_name="events",
            name="organizer",
        ),
        migrations.RemoveField(
            model_name="judge",
            name="event_tabulation",
        ),
        migrations.RemoveField(
            model_name="judgeprofile",
            name="judge",
        ),
        migrations.RemoveField(
            model_name="judgeprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="event",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="studentfine",
        ),
        migrations.RemoveField(
            model_name="studentfine",
            name="group",
        ),
        migrations.RemoveField(
            model_name="studentfine",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentfine",
            name="user",
        ),
        migrations.DeleteModel(
            name="Contestant",
        ),
        migrations.DeleteModel(
            name="Criteria",
        ),
        migrations.DeleteModel(
            name="CriteriaScores",
        ),
        migrations.DeleteModel(
            name="Events",
        ),
        migrations.DeleteModel(
            name="EventTabulation",
        ),
        migrations.DeleteModel(
            name="Judge",
        ),
        migrations.DeleteModel(
            name="JudgeProfile",
        ),
        migrations.DeleteModel(
            name="StudentAttendance",
        ),
        migrations.DeleteModel(
            name="StudentFine",
        ),
    ]
